# Generated by Django 5.2.3 on 2025-06-18 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesional',
            name='piso',
        ),
    ]
